### ISSUE TITLE
LinqToTwitter.AspNet - MentionsTimeline missing?

### ISSUE THREAD

**Issue by cskardon** [JoeMayo/LinqToTwitter#220]
Hi there, 

I've been playing with LinqToTwitter (which is excellent by the way) - and was moving my play code into a Blazor app just to see how easy it was - so I used the Blazor Demo - I copied my code across, and got an error code wise as `MentionsTimeline` isn't a member of the `TweetType` type.

So - I added `LinqToTwitter` 6 to the demo, which clears the compilation issue, but - when I try to do Auth - I get a `MissingMethodException` (basically the same as #218) - removing the dependency fixes that, but I can't get the mentions.

Is this intentional? i.e. will the AspNet part contain the Mentions at somepoint?

This is what I was running.

```
var tweetResponse = await twitterCtx.Tweets
         .Where(t => t.Type == TweetType.MentionsTimeline && t.ID == userId && t.Expansions == "author_id" )
         .SingleOrDefaultAsync();
```

I'm not sure why having both packages causes the issue.

Charlotte

**Comment by JoeMayo** [comment]
Thanks for letting me know - I'll try to repro.

**Comment by JoeMayo** [comment]
What's happening is that the LinqToTwitter.AspNet package is referencing an older version of the LinqToTwitter package/assembly. Upgrading the LinqToTwitter NuGet package should fix the problem.

I'm getting ready to release another version of LinqToTwitter. Moving forward, I'll also release LinqToTwitter.AspNet simultaneously to ensure it references the proper version of LinqToTwitter. In the previous version, all this code was in the same assembly. However, I decoupled them in v6.x because it wasn't necessary for non-ASP.NET apps to carry the extra dependencies.

**Comment by cskardon** [comment]
Hello!

Interesting, I have LinqToTwitter AspNet 6.0.1 and LinqToTwitter 6.6.0 and I still get the error.

I've cleared the caches, recompiled and still get the error.

Is there a newer version I'm not able to see?

Thanks!

**Comment by JoeMayo** [comment]
Thanks for the follow-up - I'll keep looking at this.

**Comment by JoeMayo** [comment]
Just following up - I believe this was fixed in v6.7.1. I recall being able to finally reproduce and the problem was caused by how I configured the NuGet package.
